language: objective-c

global:
 - "MODULE_NAME=com.testfairy.titestfairy"

before_install:
 - MODULE_ROOT=$PWD

install:
 - cd $MODULE_ROOT
 - curl -o install.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/install.sh
 - bash -x install.sh
 
script: 
 - curl -o script.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/script.sh
 - bash -x script.sh
 - find .
 
